
// const topics = [
//   "Shocking Facts About Human Body You Never Knew",
//   "Mind Blowing Facts About Food And Your Brain",
//   "Disgusting Facts About The Food You Eat Every Day",
//   "Surprising Facts About Human Digestion",
//   "Crazy Facts About What Happens When You Sleep",
//   "Shocking Facts About Sugar And Your Body",
//   "Wild Facts About Human Reproduction",
//   "Insane Facts About What Alcohol Does To Your Body",
//   "Disgusting Truth About Fast Food Ingredients",
//   "Mind Blowing Facts About The Human Heart",
//   "Shocking Facts About What Happens During Kissing",
//   "Crazy Facts About Human DNA You Wont Believe",
//   "Surprising Facts About Chocolate And Your Brain",
//   "Wild Facts About What Coffee Does To Your Body",
//   "Insane Facts About Human Memory",
//   "Shocking Facts About What Happens When You Blush",
//   "Disgusting Facts About The Human Mouth",
//   "Mind Blowing Facts About Spicy Food And Pain",
//   "Crazy Facts About Human Attraction",
//   "Surprising Facts About What Happens When You Laugh",
//   "Wild Facts About The Human Nose And Smell",
//   "Insane Facts About What Stress Does To Your Body",
//   "Shocking Facts About Human Touch And Skin",
//   "Disgusting Facts About What Happens When You Sneeze",
//   "Mind Blowing Facts About Human Eyes",
//   "Crazy Facts About What Happens When You Fall In Love",
//   "Surprising Facts About Human Sweat",
//   "Wild Facts About What Happens When You Cry",
//   "Insane Facts About The Human Stomach",
//   "Shocking Facts About What Food Does To Your Mood",
//   "Disgusting Facts About Human Hair",
//   "Mind Blowing Facts About What Happens During Exercise",
//   "Crazy Facts About Human Taste Buds",
//   "Surprising Facts About What Music Does To Your Brain",
//   "Wild Facts About Human Blood",
//   "Insane Facts About What Happens When You Get Angry",
//   "Shocking Facts About Human Bones",
//   "Disgusting Facts About What Happens When You Eat Too Much",
//   "Mind Blowing Facts About Human Hormones",
//   "Crazy Facts About What Happens When You Hold Your Breath",
// ];

// function getRandomTopic() {
//   const index = Math.floor(Math.random() * topics.length);
//   return topics[index];
// }

// module.exports = { getRandomTopic };


// topicsManager.js

// const topics = [

// /* ================= CHILDREN FACTS (50) ================= */

// "Shocking Facts About Children's Brain Development",
// "Mind Blowing Facts About Why Kids Learn Faster",
// "Crazy Facts About Why Children Ask So Many Questions",
// "Surprising Facts About Children's Memory",
// "Wild Facts About How Babies Recognize Faces",
// "Insane Facts About How Children Learn Languages",
// "Shocking Facts About Children's Imagination",
// "Mind Blowing Facts About Why Kids Love Cartoons",
// "Crazy Facts About Child Growth Speed",
// "Surprising Facts About Children's Sleep Needs",
// "Wild Facts About Baby Reflexes",
// "Insane Facts About Child Learning Ability",
// "Shocking Facts About Children's Curiosity",
// "Mind Blowing Facts About Child Brain Connections",
// "Crazy Facts About Why Kids Repeat Words",
// "Surprising Facts About Child Attention Span",
// "Wild Facts About Child Development Stages",
// "Insane Facts About Children's Hearing Ability",
// "Shocking Facts About Children's Vision Development",
// "Mind Blowing Facts About How Kids Learn Walking",
// "Crazy Facts About Child Emotional Growth",
// "Surprising Facts About Child Social Skills",
// "Wild Facts About Child Memory Formation",
// "Insane Facts About Child Creativity",
// "Shocking Facts About Why Kids Ask Why",
// "Mind Blowing Facts About Child Brain Plasticity",
// "Crazy Facts About Child Learning Speed",
// "Surprising Facts About Child Growth Hormones",
// "Wild Facts About Child Brain Size",
// "Insane Facts About Child Language Skills",
// "Shocking Facts About Child Play Behavior",
// "Mind Blowing Facts About Child Imagination Power",
// "Crazy Facts About Child Problem Solving",
// "Surprising Facts About Child Curiosity",
// "Wild Facts About Child Energy Levels",
// "Insane Facts About Child Brain Growth",
// "Shocking Facts About Child Learning Patterns",
// "Mind Blowing Facts About Child Memory Power",
// "Crazy Facts About Child Emotional Reactions",
// "Surprising Facts About Child Attention",
// "Wild Facts About Child Thinking Skills",
// "Insane Facts About Child Brain Activity",
// "Shocking Facts About Child Social Development",
// "Mind Blowing Facts About Child Intelligence",
// "Crazy Facts About Child Brain Signals",
// "Surprising Facts About Child Learning Habits",
// "Wild Facts About Child Brain Functions",
// "Insane Facts About Child Focus Ability",
// "Shocking Facts About Child Brain Development Speed",
// "Mind Blowing Facts About Child Growth Patterns",

// /* ================= FOOD FACTS (50) ================= */

// "Disgusting Facts About Fast Food Ingredients",
// "Shocking Facts About Sugar And Your Body",
// "Mind Blowing Facts About Junk Food Effects",
// "Crazy Facts About What Happens When You Eat Too Much Sugar",
// "Surprising Facts About Healthy Foods That Boost Memory",
// "Wild Facts About Hidden Sugar In Drinks",
// "Insane Facts About Processed Food",
// "Shocking Facts About Fried Food Effects",
// "Mind Blowing Facts About Salt Consumption",
// "Crazy Facts About Artificial Flavors",
// "Surprising Facts About Food Preservatives",
// "Wild Facts About Packaged Food",
// "Insane Facts About Food Coloring",
// "Shocking Facts About Fast Food Calories",
// "Mind Blowing Facts About Sugar Addiction",
// "Crazy Facts About Junk Food Cravings",
// "Surprising Facts About Food Digestion",
// "Wild Facts About Overeating",
// "Insane Facts About Food Chemicals",
// "Shocking Facts About Soda Drinks",
// "Mind Blowing Facts About Food Labels",
// "Crazy Facts About Food Processing",
// "Surprising Facts About Food Storage",
// "Wild Facts About Frozen Food",
// "Insane Facts About Food Shelf Life",
// "Shocking Facts About Street Food Hygiene",
// "Mind Blowing Facts About Cooking Oil",
// "Crazy Facts About Food Bacteria",
// "Surprising Facts About Expired Food",
// "Wild Facts About Fast Food Chains",
// "Insane Facts About Food Packaging",
// "Shocking Facts About Sugar Levels",
// "Mind Blowing Facts About Food Additives",
// "Crazy Facts About Food Digestion Time",
// "Surprising Facts About Eating Speed",
// "Wild Facts About Food Temperature",
// "Insane Facts About Food Safety",
// "Shocking Facts About Food Calories",
// "Mind Blowing Facts About Food Energy",
// "Crazy Facts About Food Nutrition",
// "Surprising Facts About Food Absorption",
// "Wild Facts About Food Metabolism",
// "Insane Facts About Food Breakdown",
// "Shocking Facts About Food Consumption",
// "Mind Blowing Facts About Food Processing Speed",
// "Crazy Facts About Food Energy Use",
// "Surprising Facts About Food Consumption Habits",
// "Wild Facts About Food Intake",
// "Insane Facts About Food Effects On Body",
// "Shocking Facts About Food Digestion Process",

// /* ================= ORGAN FACTS (50) ================= */

// "Mind Blowing Facts About The Human Brain",
// "Shocking Facts About The Human Heart",
// "Crazy Facts About The Human Liver",
// "Surprising Facts About The Human Kidneys",
// "Wild Facts About The Human Lungs",
// "Insane Facts About The Human Stomach",
// "Shocking Facts About The Human Skin",
// "Mind Blowing Facts About The Human Eyes",
// "Crazy Facts About The Human Intestine",
// "Surprising Facts About The Human Pancreas",
// "Wild Facts About The Human Gallbladder",
// "Insane Facts About The Human Spleen",
// "Shocking Facts About The Human Bladder",
// "Mind Blowing Facts About The Human Thyroid",
// "Crazy Facts About The Human Colon",
// "Surprising Facts About The Human Nervous System",
// "Wild Facts About The Human Circulatory System",
// "Insane Facts About The Human Digestive System",
// "Shocking Facts About The Human Endocrine System",
// "Mind Blowing Facts About The Human Respiratory System",
// "Crazy Facts About The Human Immune System",
// "Surprising Facts About The Human Skeletal System",
// "Wild Facts About The Human Muscular System",
// "Insane Facts About The Human Brain Signals",
// "Shocking Facts About The Human Blood Flow",
// "Mind Blowing Facts About The Human Heartbeat",
// "Crazy Facts About The Human Brain Activity",
// "Surprising Facts About The Human Nerves",
// "Wild Facts About The Human Oxygen Flow",
// "Insane Facts About The Human Digestion",
// "Shocking Facts About The Human Body Systems",
// "Mind Blowing Facts About The Human Brain Power",
// "Crazy Facts About The Human Organ Functions",
// "Surprising Facts About The Human Blood Cells",
// "Wild Facts About The Human Body Control",
// "Insane Facts About The Human Organ Speed",
// "Shocking Facts About The Human Body Regulation",
// "Mind Blowing Facts About The Human Body Balance",
// "Crazy Facts About The Human Body Signals",
// "Surprising Facts About The Human Organ Communication",
// "Wild Facts About The Human Body Response",
// "Insane Facts About The Human Body Reactions",
// "Shocking Facts About The Human Organ Coordination",
// "Mind Blowing Facts About The Human Body Performance",
// "Crazy Facts About The Human Organ Activity",
// "Surprising Facts About The Human Body Movement",
// "Wild Facts About The Human Organ Efficiency",
// "Insane Facts About The Human Body Control System",
// "Shocking Facts About The Human Body Functions",
// "Mind Blowing Facts About The Human Organ System",

// /* ================= PSYCHOLOGY FACTS (50) ================= */

// "Crazy Facts About Human Attraction",
// "Surprising Facts About Why People Fall In Love",
// "Mind Blowing Facts About Human Behavior",
// "Shocking Facts About Body Language",
// "Wild Facts About Why We Feel Emotions",
// "Insane Facts About Human Memory",
// "Shocking Facts About Human Decisions",
// "Mind Blowing Facts About Human Thinking",
// "Crazy Facts About Human Reactions",
// "Surprising Facts About Human Emotions",
// "Wild Facts About Human Motivation",
// "Insane Facts About Human Confidence",
// "Shocking Facts About Human Habits",
// "Mind Blowing Facts About Human Focus",
// "Crazy Facts About Human Attention",
// "Surprising Facts About Human Fear",
// "Wild Facts About Human Stress",
// "Insane Facts About Human Anxiety",
// "Shocking Facts About Human Happiness",
// "Mind Blowing Facts About Human Mood",
// "Crazy Facts About Human Personality",
// "Surprising Facts About Human Behavior Patterns",
// "Wild Facts About Human Mental Health",
// "Insane Facts About Human Thinking Speed",
// "Shocking Facts About Human Brain Tricks",
// "Mind Blowing Facts About Human Learning",
// "Crazy Facts About Human Behavior Change",
// "Surprising Facts About Human Motivation Levels",
// "Wild Facts About Human Emotions Control",
// "Insane Facts About Human Brain Response",
// "Shocking Facts About Human Reaction Time",
// "Mind Blowing Facts About Human Brain Signals",
// "Crazy Facts About Human Decision Making",
// "Surprising Facts About Human Mind Control",
// "Wild Facts About Human Brain Functions",
// "Insane Facts About Human Thinking Patterns",
// "Shocking Facts About Human Attention Span",
// "Mind Blowing Facts About Human Brain Activity",
// "Crazy Facts About Human Memory Power",
// "Surprising Facts About Human Emotional Response",
// "Wild Facts About Human Mental Strength",
// "Insane Facts About Human Thought Process",
// "Shocking Facts About Human Behavior Response",
// "Mind Blowing Facts About Human Brain Performance",
// "Crazy Facts About Human Mind Behavior",
// "Surprising Facts About Human Brain Processing",
// "Wild Facts About Human Mind Activity",
// "Insane Facts About Human Brain Efficiency",
// "Shocking Facts About Human Brain Control",
// "Mind Blowing Facts About Human Thinking Ability",

// /* ================= DAILY USAGE FACTS (50) ================= */

// "Crazy Facts About Why We Blink",
// "Surprising Facts About Why We Yawn",
// "Wild Facts About Why We Get Goosebumps",
// "Insane Facts About Why We Feel Hungry",
// "Shocking Facts About Why We Feel Thirsty",
// "Mind Blowing Facts About Why We Sweat",
// "Crazy Facts About Why We Feel Tired",
// "Surprising Facts About Why We Stretch",
// "Wild Facts About Why We Feel Cold",
// "Insane Facts About Why We Feel Hot",
// "Shocking Facts About Why We Feel Pain",
// "Mind Blowing Facts About Why We Breathe",
// "Crazy Facts About Why We Walk",
// "Surprising Facts About Why We Run",
// "Wild Facts About Why We Sleep",
// "Insane Facts About Why We Dream",
// "Shocking Facts About Why We Laugh",
// "Mind Blowing Facts About Why We Cry",
// "Crazy Facts About Why We Sneeze",
// "Surprising Facts About Why We Cough",
// "Wild Facts About Why We Talk",
// "Insane Facts About Why We Listen",
// "Shocking Facts About Why We See",
// "Mind Blowing Facts About Why We Hear",
// "Crazy Facts About Why We Smell",
// "Surprising Facts About Why We Taste",
// "Wild Facts About Why We Move",
// "Insane Facts About Why We Think",
// "Shocking Facts About Why We Remember",
// "Mind Blowing Facts About Why We Forget",
// "Crazy Facts About Why We Feel Emotions",
// "Surprising Facts About Why We Feel Fear",
// "Wild Facts About Why We Feel Happy",
// "Insane Facts About Why We Feel Sad",
// "Shocking Facts About Why We Feel Angry",
// "Mind Blowing Facts About Why We Feel Excited",
// "Crazy Facts About Why We Feel Nervous",
// "Surprising Facts About Why We Feel Relaxed",
// "Wild Facts About Why We Feel Sleepy",
// "Insane Facts About Why We Feel Awake",
// "Shocking Facts About Why We Feel Hungry Again",
// "Mind Blowing Facts About Why We Feel Energy",
// "Crazy Facts About Why We Feel Weak",
// "Surprising Facts About Why We Feel Strong",
// "Wild Facts About Why We Feel Calm",
// "Insane Facts About Why We Feel Stressed",
// "Shocking Facts About Why We Feel Comfortable",
// "Mind Blowing Facts About Why We Feel Uncomfortable",
// "Crazy Facts About Why We Feel Balanced",
// "Surprising Facts About Why We Feel Dizzy"

// ];

// let availableTopics = [];

// function shuffle(array) {
//   for (let i = array.length - 1; i > 0; i--) {
//     const j = Math.floor(Math.random() * (i + 1));
//     [array[i], array[j]] = [array[j], array[i]];
//   }
//   return array;
// }

// function getRandomTopic() {
//   if (availableTopics.length === 0) {
//     availableTopics = shuffle([...topics]);
//     console.log("All topics used. Resetting topic list...");
//   }

//   return availableTopics.pop();
// }

// module.exports = { getRandomTopic };






const topics = [

/* ================= CHILDREN FACTS (50) ================= */

"What Happens to a Baby's Brain in the First 1000 Days",
"Why Bilingual Kids Are Smarter Than You Think",
"The Scary Truth About Screen Time and Kids' Brains",
"Shocking Facts About Children's Brain Development",
"Why Kids Learn Languages Faster Than Adults — The Science",
"Crazy Facts About Why Children Ask So Many Questions",
"What Really Happens Inside a Child's Brain While They Sleep",
"Surprising Facts About Children's Memory Power",
"Wild Facts About How Babies Recognize Faces From Birth",
"Why Do Kids Repeat Words? The Science Behind It",
"Mind Blowing Facts About Child Brain Plasticity",
"Insane Facts About How Fast Children's Brains Grow",
"Why Children Forget Things — Surprising Brain Science",
"Crazy Facts About Child Emotional Growth Stages",
"Surprising Facts About Child Social Skills Development",
"Wild Facts About How Babies First See the World",
"Shocking Facts About Children's Imagination Ability",
"The Weird Reason Kids Love Cartoons So Much",
"Mind Blowing Facts About Child Brain Connections",
"Why Do Kids Have So Much Energy? Science Explained",
"Crazy Facts About Child Problem Solving Skills",
"Insane Facts About Child Creativity Levels",
"Surprising Facts About How Babies Learn to Walk",
"Wild Facts About Child Attention Span Limits",
"Shocking Facts About Child Brain Activity at Night",
"What No One Tells You About Child Development Stages",
"Mind Blowing Facts About Child Intelligence Signs",
"The Dark Truth About How Stress Affects Kids' Brains",
"Crazy Facts About Child Growth Hormone Patterns",
"Surprising Facts About Children's Hearing Ability",
"Wild Facts About Child Learning Speed vs Adults",
"Insane Facts About Children's Vision Development",
"Why Some Kids Are More Curious Than Others — Explained",
"Shocking Facts About Child Brain Size at Birth",
"Mind Blowing Facts About Child Language Skill Growth",
"Crazy Facts About Why Kids Play Pretend",
"Surprising Facts About Child Brain Growth Patterns",
"Wild Facts About Child Memory Formation Speed",
"Insane Facts About Child Focus Ability Limits",
"Shocking Facts About Child Learning Pattern Differences",
"How a Child's Brain Reacts to Fear — Disturbing Facts",
"Mind Blowing Facts About Child Thinking Skills",
"Crazy Facts About Child Brain Signal Speed",
"Surprising Facts About Child Social Development Stages",
"Wild Facts About Child Brain Function Changes",
"Insane Facts About Child Emotional Reaction Triggers",
"Shocking Facts About Child Attention and Focus",
"Mind Blowing Facts About Child Growth Rate Patterns",
"Crazy Facts About Child Brain Development Speed",
"Why Babies Smile in Their Sleep — The Real Reason",

/* ================= FOOD FACTS (50) ================= */

"What Sugar Does to Your Brain in 30 Minutes",
"Why Fast Food is Literally Designed to Addict You",
"The Shocking Truth About So-Called Healthy Packaged Foods",
"Disgusting Facts About Fast Food Ingredients",
"Shocking Facts About Sugar and Your Body",
"What Happens to Your Body When You Eat Too Much Sugar",
"Wild Facts About Hidden Sugar in Drinks",
"How Long Does Junk Food Stay in Your Body? Insane Facts",
"Shocking Facts About Fried Food Effects on Organs",
"The Real Reason You Crave Junk Food at Night",
"Mind Blowing Facts About Salt Consumption Effects",
"Crazy Facts About Artificial Flavors — What You're Really Eating",
"Surprising Facts About Food Preservatives in Your Body",
"Wild Facts About What Packaged Food Does to You",
"Insane Facts About Food Coloring and Your Brain",
"Shocking Facts About Fast Food Calorie Counts",
"Mind Blowing Facts About Sugar Addiction Science",
"Crazy Facts About Why Junk Food Cravings Are So Strong",
"Surprising Facts About How Long Food Takes to Digest",
"Wild Facts About What Overeating Does to Your Stomach",
"Insane Facts About Chemicals in Processed Food",
"What Soda Does to Your Body — Shocking Facts",
"Mind Blowing Facts About What Food Labels Hide From You",
"Crazy Facts About How Food Is Actually Processed",
"Surprising Facts About Frozen Food vs Fresh Food",
"Wild Facts About How Long Packaged Food Really Lasts",
"Insane Facts About Street Food Hygiene Secrets",
"Shocking Facts About What Cooking Oil Does Inside You",
"Mind Blowing Facts About Bacteria Growing in Your Food",
"The Truth About Expired Food That Nobody Tells You",
"Wild Facts About Fast Food Chain Ingredient Secrets",
"Insane Facts About Food Packaging Chemicals",
"Shocking Facts About How Fast Blood Sugar Spikes",
"Mind Blowing Facts About Food Additive Effects",
"Crazy Facts About How Fast Food Is Digested",
"Surprising Facts About Eating Speed and Weight Gain",
"Wild Facts About Food Temperature and Bacteria",
"Insane Facts About Food Safety Risks You Ignore Daily",
"Shocking Facts About Calorie Differences in Foods",
"Mind Blowing Facts About Food Energy in Your Body",
"Crazy Facts About Food Nutrition Myths Debunked",
"Surprising Facts About How Food Is Absorbed",
"Wild Facts About Metabolism and Food",
"Insane Facts About How Your Body Breaks Down Food",
"Shocking Facts About Daily Food Consumption Habits",
"Mind Blowing Facts About Food Processing Speed in Body",
"Crazy Facts About Food Energy Usage in Your Body",
"Surprising Facts About Your Daily Food Intake",
"What Healthy Foods Actually Do to Your Brain",
"Insane Facts About Food Effects on Your Organs",

/* ================= ORGAN FACTS (50) ================= */

"What Happens to Your Heart When You're Scared",
"Your Gut Has Its Own Brain — Here's the Proof",
"How Your Liver Saves Your Life Every Single Day",
"Mind Blowing Facts About the Human Brain",
"Shocking Facts About the Human Heart Rate Limits",
"Crazy Facts About What Your Liver Actually Does",
"Surprising Facts About the Human Kidneys' Work Rate",
"Wild Facts About the Human Lungs' Capacity",
"Insane Facts About What Your Stomach Does at Night",
"Shocking Facts About the Human Skin as an Organ",
"Mind Blowing Facts About Human Eye Movement Speed",
"Crazy Facts About the Human Intestine Length",
"Surprising Facts About What the Pancreas Controls",
"Wild Facts About the Human Gallbladder's Role",
"Insane Facts About the Human Spleen's Functions",
"What Happens to Your Kidneys When You're Dehydrated",
"Mind Blowing Facts About the Human Thyroid Control",
"Crazy Facts About the Human Colon's Work",
"Surprising Facts About the Human Nervous System Speed",
"Wild Facts About the Human Circulatory System Volume",
"Insane Facts About the Human Digestive System Daily",
"Shocking Facts About the Human Endocrine System",
"Mind Blowing Facts About the Human Respiratory System",
"The Disgusting Truth About What Your Immune System Fights Daily",
"Surprising Facts About the Human Skeletal System Changes",
"Wild Facts About the Human Muscular System Strength",
"Insane Facts About Human Brain Signal Speed",
"Shocking Facts About Human Blood Flow Volume Per Day",
"Mind Blowing Facts About the Human Heartbeat Per Lifetime",
"Crazy Facts About Human Brain Activity During Sleep",
"Surprising Facts About How Your Nerves Send Signals",
"Wild Facts About Human Oxygen Flow Through the Body",
"Insane Facts About Human Digestion Time Per Meal",
"Shocking Facts About How All Body Systems Talk to Each Other",
"Mind Blowing Facts About Human Brain Power Usage",
"Crazy Facts About Every Organ's Hidden Functions",
"Surprising Facts About Human Blood Cell Lifespan",
"Wild Facts About How Your Body Regulates Temperature",
"Insane Facts About Organ Reaction Speed in Emergencies",
"Shocking Facts About How Your Body Fixes Itself at Night",
"Mind Blowing Facts About Human Body Balance Systems",
"Crazy Facts About How Organs Signal Each Other",
"Surprising Facts About Organ Communication Timing",
"Wild Facts About the Body's Fastest Organ Responses",
"Insane Facts About How Your Organs React to Stress",
"Shocking Facts About Organ Coordination in Crisis",
"Mind Blowing Facts About What Your Body Does in 1 Second",
"Crazy Facts About Organ Activity While You Sleep",
"Surprising Facts About How Organs Age Differently",
"Wild Facts About the Most Efficient Organ in Your Body",

/* ================= PSYCHOLOGY FACTS (50) ================= */

"Why Your Brain Lies to You Every Single Day",
"The Psychology of Why You Procrastinate",
"Dark Facts About How Social Media Rewires Your Brain",
"Crazy Facts About Human Attraction Science",
"Surprising Facts About Why People Fall in Love",
"Mind Blowing Facts About How the Brain Makes Decisions",
"Shocking Facts About What Your Body Language Says About You",
"Wild Facts About Why We Feel Emotions So Strongly",
"Insane Facts About Human Memory Tricks and Failures",
"Why We Make Bad Decisions Under Pressure — Explained",
"Mind Blowing Facts About Human Thinking Speed Limits",
"Crazy Facts About Human Reactions to Fear",
"Surprising Facts About Human Emotions and the Body",
"Wild Facts About What Drives Human Motivation",
"Insane Facts About Human Confidence and the Brain",
"Shocking Facts About How Habits Form in the Brain",
"Why You Can't Focus — The Real Scientific Reason",
"Crazy Facts About Human Attention Limits",
"Surprising Facts About What Makes Humans Afraid",
"Wild Facts About the Science of Human Stress",
"Insane Facts About What Anxiety Does to Your Brain",
"Shocking Facts About What Makes Humans Happy",
"Mind Blowing Facts About Human Mood Shifts",
"Crazy Facts About Personality Type Science",
"Surprising Facts About Human Behavior Patterns",
"Wild Facts About Mental Health and Daily Life",
"Insane Facts About Human Thinking Speed",
"Shocking Brain Tricks That Control Your Behavior",
"Mind Blowing Facts About How Humans Learn Things",
"Crazy Facts About What Makes Humans Change Behavior",
"Surprising Facts About Human Motivation Levels",
"Wild Facts About Controlling Human Emotions",
"Insane Facts About Brain Response Time",
"Shocking Facts About Human Reaction Speed",
"Mind Blowing Facts About Brain Signal Patterns",
"Why You Always Think You're Right — Psychology Explained",
"Surprising Facts About Human Mind Control Triggers",
"Wild Facts About Human Brain Functions Under Stress",
"Insane Facts About Human Thought Patterns",
"Shocking Facts About Human Attention Span in 2025",
"Mind Blowing Facts About Brain Activity Per Second",
"Crazy Facts About Human Memory Failures",
"Surprising Facts About Emotional Response Triggers",
"Wild Facts About Human Mental Strength Limits",
"Insane Facts About How Humans Process Thoughts",
"Shocking Facts About What Controls Human Behavior",
"Mind Blowing Facts About Brain Performance Peaks",
"Crazy Facts About Human Mind and Daily Decisions",
"The Hidden Psychology Behind Why You Buy Things",
"Mind Blowing Facts About Human Thinking Ability Limits",

/* ================= DAILY BODY FACTS (50) ================= */

"Why You Always Wake Up at 3AM — Real Science",
"Why You Yawn When Someone Else Yawns — Explained",
"The Real Reason You Get Goosebumps",
"Crazy Facts About Why We Blink So Often",
"Insane Facts About Why We Feel Hungry Every Few Hours",
"Shocking Facts About Why We Feel Thirsty",
"Mind Blowing Facts About Why Humans Sweat",
"Crazy Facts About Why We Feel Tired Mid-Day",
"Surprising Facts About Why We Stretch After Sleeping",
"Wild Facts About Why We Feel Cold and Shiver",
"Insane Facts About Why We Feel Too Hot",
"Shocking Facts About Why We Feel Pain in Our Brain",
"Mind Blowing Facts About the Science of Breathing",
"Crazy Facts About Why Humans Walk the Way We Do",
"Surprising Facts About What Happens When You Run",
"Why Do Humans Need Sleep? The Real Answer",
"Insane Facts About What Happens When You Dream",
"Shocking Facts About Why We Laugh at Things",
"Mind Blowing Facts About Why Humans Cry",
"Crazy Facts About Why We Sneeze So Violently",
"Surprising Facts About Why We Cough Involuntarily",
"Wild Facts About How Talking Uses Your Brain",
"Insane Facts About How We Actually Hear Sounds",
"Shocking Facts About How Human Vision Really Works",
"Mind Blowing Facts About Smell and Memory Connection",
"Crazy Facts About Why Taste Changes as You Age",
"Wild Facts About How Your Body Moves Without Thinking",
"Insane Facts About How the Brain Decides Everything",
"Shocking Facts About Why We Remember Some Things Forever",
"Mind Blowing Facts About Why We Forget Things Fast",
"The Real Reason You Cry Watching Movies",
"Surprising Facts About Why Humans Fear the Dark",
"Wild Facts About What Actually Makes You Happy",
"Insane Facts About Why We Feel Sad Randomly",
"Why Do We Get Angry So Fast? Brain Science Explained",
"Mind Blowing Facts About What Causes Excitement",
"Crazy Facts About Why We Feel Nervous Before Events",
"Surprising Facts About What Relaxes the Human Body",
"Wild Facts About Why We Feel Sleepy After Eating",
"Insane Facts About Why Some People Never Feel Tired",
"Shocking Facts About Why You Feel Hungry Again So Fast",
"Mind Blowing Facts About Human Energy Levels",
"Crazy Facts About Why We Feel Weak Sometimes",
"Surprising Facts About What Makes You Feel Strong",
"Wild Facts About What Calms the Nervous System",
"Insane Facts About What Triggers Stress Instantly",
"Shocking Facts About Why Your Body Gets Comfortable",
"Mind Blowing Facts About Why We Feel Uncomfortable",
"Crazy Facts About What Keeps the Body Balanced",
"Why Do We Get Dizzy? The Surprising Brain Reason",

/* ================= RELATIONSHIP FACTS (30) ================= */

"Why We Fall for the Wrong People — Psychology Explained",
"What Your Eyes Do When You're in Love",
"The Science of Why We Miss Someone",
"Why Do We Get Jealous? The Dark Science Behind It",
"What Happens to Your Brain When You Get Rejected",
"The Real Reason Some People Fall in Love Faster",
"Why Your Heart Hurts When You Break Up — For Real",
"What Attraction Really Is — Not What You Think",
"Shocking Facts About What Makes Someone Attractive",
"Why Long Distance Relationships Fail — Science Says",
"What Happens to Your Body When You Hug Someone",
"Mind Blowing Facts About Love and Brain Chemistry",
"Crazy Facts About Why We Trust Some People Instantly",
"Why Do We Feel Lonely Even Around People?",
"Surprising Facts About What Makes a Relationship Last",
"Wild Facts About Attraction Signals We Send Without Knowing",
"Insane Facts About How Breakups Affect the Brain",
"Shocking Facts About First Impressions and the Brain",
"The Weird Reason We Find Familiar Faces More Attractive",
"Why Couples Start to Look Alike Over Time — Explained",
"Mind Blowing Facts About Emotional Bonding Science",
"What Oxytocin Really Does to Your Feelings",
"Crazy Facts About Why We Idealize People We Like",
"Why Do We Ignore Red Flags? Brain Science Explains",
"Surprising Facts About Human Touch and Emotions",
"Wild Facts About Why Friends Become More Than Friends",
"Insane Facts About Attraction Across Cultures",
"Shocking Facts About How Love Changes Your Personality",
"The Science of Why Some Bonds Last a Lifetime",
"Mind Blowing Facts About How Arguments Affect the Brain",

/* ================= SLEEP AND DREAMS FACTS (30) ================= */

"Why Your Body Jerks Right Before You Fall Asleep",
"What Your Dreams Are Actually Telling You",
"Why You Forget Your Dreams Within Minutes",
"The Dark Truth About What Sleep Deprivation Does to You",
"Why You Feel Paralyzed When You Wake Up — Explained",
"Can You Really Learn While You Sleep? The Answer Shocks",
"Why We Dream About People We Haven't Thought About in Years",
"What Happens to Your Brain in the First 90 Minutes of Sleep",
"Shocking Facts About How Little Sleep You Actually Need",
"Mind Blowing Facts About REM Sleep and Memory",
"Why Nightmares Happen — The Real Brain Science",
"Crazy Facts About Sleepwalking and the Brain",
"What Sleep Deprivation Does to Your Face and Body",
"Insane Facts About How Long Humans Can Go Without Sleep",
"Why Some People Remember Every Dream They Have",
"Wild Facts About Sleep Cycles and What They Do",
"Shocking Facts About How Animals Sleep Differently",
"Mind Blowing Facts About Dreams and Emotions",
"Crazy Facts About Why We Sleep in Phases",
"The Terrifying Reality of Sleep Paralysis Explained",
"Surprising Facts About What Deep Sleep Repairs in You",
"Wild Facts About What the Brain Does at 3AM",
"Why Your Best Ideas Come Right Before Sleep",
"Insane Facts About Lucid Dreaming Science",
"Shocking Facts About Sleep and Weight Gain Connection",
"Mind Blowing Facts About How Babies Sleep Differently",
"Crazy Facts About How Much of Life You Spend Sleeping",
"Why You Dream in Black and White Sometimes — Explained",
"Surprising Facts About Snoring and Brain Health",
"Wild Facts About Sleep and Your Immune System Link",

];

let availableTopics = [];

function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

function getRandomTopic() {
  if (availableTopics.length === 0) {
    availableTopics = shuffle([...topics]);
    console.log("All topics used. Resetting topic list...");
  }

  return availableTopics.pop();
}

module.exports = { getRandomTopic };